const express = require("express");
const app = express();
const router = express.Router();
const path = require("path");
const log = require("../middleware/logger");
const setting = require("../config/setting");
const env = require("../config/env");
const lang = require("../lang/langApp");

const pageRouter = require("./pages/index");
const bankRouter = require("./bank/index");
const companyRouter = require("./company/index");
const departmentRouter = require("./department/index");
const finDownRouter = require("./finDown/index");
const finLoanRouter = require("./finLoan/index");
const finOtherRouter = require("./finOther/index");
const finTranferRouter = require("./finTranfer/index");
const groupRouter = require("./group/index");
const groupProRouter = require("./groupPro/index");
const priceListRouter = require("./pirceList/index");
const prositionRouter = require("./position/index");
const proItermsRouter = require("./proItems/index");
const projectRouter = require("./project/index");
const quotationRouter = require("./quotation/index");
const receiptRouter = require("./receipt/index");
const roomPlanRouter = require("./roomPlan/index");
const runningRouter = require("./running/index");
const targetPlanRouter = require("./targetPlan/index");
const uploadRouter = require("./upload/index");
const usersRouter = require("./users/index");
const authenRouter = require("./authen/index");

router.use("/", pageRouter);
router.use("/bank", bankRouter);
router.use("/company", companyRouter);
router.use("/department", departmentRouter);
router.use("/findown", finDownRouter);
router.use("/finloan", finLoanRouter);
router.use("/finother", finOtherRouter);
router.use("/fintranfer", finTranferRouter);
router.use("/group", groupRouter);
router.use("/grouppro", groupProRouter);
router.use("/pricelist", priceListRouter);
router.use("/position", prositionRouter);
router.use("/proitems", proItermsRouter);
router.use("/project", projectRouter);
router.use("/qutation", quotationRouter);
router.use("/receipt", receiptRouter);
router.use("/roomplan", roomPlanRouter);
router.use("/running", runningRouter);
router.use("/targetplan", targetPlanRouter);
router.use("/upload", uploadRouter);
router.use("/user", usersRouter);
router.use("/authen", authenRouter);

module.exports = router;
